/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f5faff",
        "tertiary-container": "#658fed",
        "on-tertiary-container": "#002763",
        "inverse-surface": "#24323a",
        "on-surface-variant": "#404752",
        "secondary-fixed": "#cbe6ff",
        "primary-container": "#2196f3",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001d36",
        "surface-container-high": "#dbeaf5",
        "outline": "#707883",
        "primary-fixed": "#d1e4ff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#00497d",
        "inverse-on-surface": "#e4f3fe",
        "on-tertiary-fixed": "#001945",
        "on-primary": "#ffffff",
        "secondary": "#21638d",
        "on-primary-container": "#002c4f",
        "on-background": "#0f1d25",
        "on-secondary-fixed-variant": "#004b71",
        "surface-container": "#e1f0fb",
        "surface-dim": "#cddce7",
        "primary": "#0061a4",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#93cdfc",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-container-highest": "#d6e5ef",
        "on-surface": "#0f1d25",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#b0c6ff",
        "tertiary-fixed": "#d9e2ff",
        "surface-tint": "#0061a4",
        "surface-container-low": "#e9f5ff",
        "on-secondary-fixed": "#001e30",
        "primary-fixed-dim": "#9ecaff",
        "on-secondary-container": "#105982",
        "outline-variant": "#bfc7d4",
        "secondary-container": "#95cfff",
        "background": "#f5faff",
        "inverse-primary": "#9ecaff",
        "on-tertiary-fixed-variant": "#00429c",
        "surface-bright": "#f5faff",
        "tertiary": "#2b5bb5",
        "surface-variant": "#d6e5ef",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "unit-xs": "0.25rem",
        "margin-desktop": "2rem",
        "unit-xxl": "3rem",
        "unit-md": "1rem",
        "unit-xl": "2rem",
        "unit-sm": "0.5rem",
        "unit-lg": "1.5rem",
        "grid-columns": "12",
        "gutter": "1.5rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-xl": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "headline-sm": ["16px", {"lineHeight": "24px", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
      },
    },
  },
  plugins: [],
}
